name: Pull Request Workflow
'on':
  pull_request:
    branches:
      - main
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Print Hello from PR
        run: echo "Hello from Pull Request!"
